<script language="JavaScript">
var gAutoPrint = true; // Flag for whether or not to automatically call the print function

function printSpecial()
{

document.getElementById("logo").style.display = "";

if (document.getElementById != null)
{
var html = '<HTML>\n<HEAD>\n';

if (document.getElementsByTagName != null)
{
var headTags = document.getElementsByTagName("head");
if (headTags.length > 0)
html += headTags[0].innerHTML;
}

html += '\n</HE' + 'AD>\n<BODY>\n';

var printReadyElem = document.getElementById("printReady");

if (printReadyElem != null)
{
html += printReadyElem.innerHTML;
}
else
{
alert("Could not find the printReady section in the HTML");
return;
}

html += '\n</BO' + 'DY>\n</HT' + 'ML>';

var printWin = window.open("","printSpecial");
printWin.document.open();
printWin.document.write(html);
printWin.document.close();
if (gAutoPrint){
	printWin.print();
	document.getElementById("logo").style.display = "none";
	}
}
else
{
alert("Sorry, the print ready feature is only available in modern browsers.");
}
}



</script>
<div id="printReady">
	<div align="center" id="logo" style="display:none">
		<table border="0">
			<tr>
				<td><img src="<?= IMAGES_PATH ?>/jhev.png" width="70px"></td>
				<td>STATISTIK ADUAN DITERIMA BAGI TAHUN 2014</td>
			</tr>
		</table>
		
	</div>
	
<table cellpadding="5" cellspacing="1"  id="unijaya" width="100%">
	<colgroup>
		<col />
		<col class="oce-first" />
	</colgroup>
	<tbody>
		
		<?php include('stat_monthdtl1.phtml'); ?>
		<?php include('stat_monthdtl2.phtml'); ?>
		<?php include('stat_monthdtl3.phtml'); ?>
		<?php include('stat_monthdtl4.phtml'); ?>
	</tbody>
</table>
</div>
<a href="javascript:void(printSpecial())">Print</a>
