<table width="100%" cellspacing="1" cellpadding="0" border="0">
	<tr>
		<td width="100%" height="100%" valign="top" colspan="2">
			<iframe src ="<?= SYSTEM_URL ?>/layout/admin/head" width="100%" height="120px" frameborder="0">
			  <p>Your browser does not support iframes.</p>
			</iframe>
		</td>
	</tr>
	<tr>
		<td width="20%" height="100%" valign="top">
			<iframe src ="<?= SYSTEM_URL ?>/menu/master" width="100%" height="420" frameborder="0" name="left">
			  <p>Your browser does not support iframes.</p>
			</iframe>
		</td>
		<td valign="top">
			<div style="margin-left:20px;margin-right:5px">
			<iframe src ="<?= SYSTEM_URL ?>/admin/user/list" marginwidth="20px" width="100%" height="420px" frameborder="0" name="right" align="top" scrolling="auto">
			  <p>Your browser does not support iframes.</p>
			</iframe>
			</div>
		</td>
	</tr>
</table>