<div class="content-header">
	<table cellspacing="0">
	    <tr>
	        <td style="width:50%;"><h3 class="icon-head head-customer"><?= $this->translate->_('Senarai Modul') ?></h3></td>
	        <td class="a-right">
	            <button type="button" class="add" onclick="setLocation('<?= $this->url ?>/admin/acl/module_add')" style=""><span><?= $this->translate->_('Tambah') ?></span></button>        
	        </td>
	    </tr>
	</table>
</div>
<br>
<?= $this->pages; ?>


