<script language=Javascript>
function Inint_AJAX() {
   try { return new ActiveXObject("Msxml2.XMLHTTP");  } catch(e) {} //IE
   try { return new ActiveXObject("Microsoft.XMLHTTP"); } catch(e) {} //IE
   try { return new XMLHttpRequest();          } catch(e) {} //Native Javascript
   alert("XMLHttpRequest not supported");
   return null;
};

function dochange(src, val) {
     var req = Inint_AJAX();
     req.onreadystatechange = function () { 
          if (req.readyState==4) {
               if (req.status==200) {
                    document.getElementById(src).innerHTML=req.responseText; //retuen value
               } 
          }
     };
     req.open("GET", "<?= SYSTEM_URL ?>/dynamic/module.php?data="+src+"&val="+val); //make connection
     req.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=iso-8859-1"); // set Header
     req.send(null); //send value
}

window.onLoad=dochange('states', -1);         // value in first dropdown
</script>

<?php if($this->entrySaved): ?>
	<p class="success"><?= $this->translate->_('Tambah privilege baru berjaya.') ?></p>
	<meta http-equiv="refresh" content=1;URL="privileges">
<?php else: ?>

<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">

	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-cms-page"><?= $this->translate->_('Tambah Privilege') ?></h3></td>
		        <td class="a-right">
		            <button type="button" class="scalable back" onclick="Javascript:history.back();" style=""><span><?= $this->translate->_('Kembali') ?></span></button>            	       
					<button type="reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Semula') ?></span></button>  
	                <button type="submit" class="scalable save" name="submit" id="submit" style=""><span><?= $this->translate->_('Simpan') ?></span></button>  
	                
	            </td>
		    </tr>
		</table>
	</div>
	<div class="entry-edit">
		<div class="fieldset " id="group_fields63">
			<p class="box"><?= $this->translate->_('Sila masukkan maklumat pada ruangan di bawah.') ?></p>
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
				<colgroup>
					<col class="oce-first" />
					<col>
				</colgroup>
				<tbody>
					<tr>
						<td width="20%"><?= $this->translate->_('Nama Privilege') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->privilege ?></td>
					</tr> 
					<tr>
						<td width="20%"><?= $this->translate->_('Keterangan') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->desc ?></td>
					</tr> 
					<tr>
						<td width="20%"><?= $this->translate->_('Modul') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->module ?></td>
					</tr> 
					<tr>
						<td width="20%"><?= $this->translate->_('Resource') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->resource ?></td>
					</tr>
					<!--<tr>
						<td width="20%"><?= $this->translate->_('Modul') ?>&nbsp;<span class="required2">*</span></td>
						<td>
							<?php 
								echo "<font id=states><select>\n";
								echo "<option value='0'>[--Pilih--]</option> \n" ;
								echo "</select></font>\n";
							?>
						</td>
					</tr> 
					<tr>
						<td width="20%"><?= $this->translate->_('Resource') ?>&nbsp;<span class="required2">*</span></td>
						<td>
							<?php 
								echo "<font id=cities><select>\n";
								echo "<option value='0'>[--Pilih--]</option> \n" ;
								echo "</select></font>\n";
							?>
						</td>
					</tr>-->
					<tr>
						<td valign="top"><?= $this->translate->_('Papar') ?>&nbsp;<span class="required2">*</span></td>
						<td align="left"><?= $this->form->show ?></td>
					</tr>
				</tbody>
			</table>
			<p class="required2" align="right">* <?= $this->translate->_('Diperlukan') ?></p>
		</div>	
	</div>
</form>
<?php endif; ?>