<div class="content-header">
	<table cellspacing="0">
	    <tr>
	        <td style="width:50%;"><h3 class="icon-head head-customer"><?= $this->translate->_('Senarai Tentera') ?></h3></td>
	        <td class="a-right">
	           <button type="button" class="add" onclick="setLocation('<?= $this->url ?>/alamat/tentera/add')" style=""><span><?= $this->translate->_('Add') ?></span></button>
	        </td>
	    </tr>
	</table>
</div>
<?= $this->pages; ?>


