<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Aduan') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bpm_report', 'month'))
									echo '<li><a href="'.SYSTEM_URL .'/bpm/report/month" target="right">'. $this->translate->_('Bulanan') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
			</div>
			<br>
			<br>
			<div align="center" style="margin-left: 20px;"><span style="font-size:10px">
			<?= $this->translate->_('Jika terdapat sebarang masalah mengenai sistem atau data, sila hubungi:') ?>
			<br><br> 
			<strong>Bahagian Pengurusan Maklumat</strong><br>Aras 20, Menara TH Perdana<br>1001 Jalan Tun Ismail<br>	50250 Kuala Lumpur<br>Telefon : 03-2050 8000<br>Email: bpmjhev@mod.gov.my<br></span>
			</div>
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>