<div class="content-header">
	<table cellspacing="0">
	    <tr>
	        <td style="width:50%;"><h3 class="icon-head head-customer"><?= $this->translate->_('Senarai Pertanyaan') ?></h3></td>
	        <td class="a-right">
	            <!--<button type="button" class="add" onclick="setLocation('<?= $this->url ?>/admin/state/add')" style=""><span><?= $this->translate->_('Tambah') ?></span></button>--> 
	        </td>
	    </tr>
	</table>
</div>
<br>
<div class="entry-edit">
	<div class="fieldset" id="group_fields63">
		<div align="left"><strong>Petunjuk:</strong></div>
		<table width="100%" cellpadding="5" cellspacing="1">
			<tr>
				<td width="10%"></td>
				<td width="30px" style="border:solid 1px #000000"></td>
				<td width="25%" align="left" valign="middle">Tiada Peringatan</td>
				<td width="30px" style="border:solid 1px #000000" class="contents_warning_3"></td>
				<td width="25%" align="left">Tamat Tempoh Lesen (1 Bulan)</td>
				<td width="30px" class="contents_warning_2"></td>
				<td width="25%" align="left">Lesen Tamat Tempoh</td>
			</tr>
		</table>
	</div>
</div>
<br>
<?php

	$arr_senarai = array(
					'0' => array(
						'nolesen' => 'TG0001',
						'namapp' => 'Saiful Izwan Bin Ibrahim',
						'jenis' => 'Nature Guide (T2)',
						'tarikh' => '02-04-2009',
						'status' => 'Tidak Aktif',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'1' => array(
						'nolesen' => 'TG0003',
						'namapp' => 'Yusri Bin Harun',
						'jenis' => 'City Guide (P)',
						'tarikh' => '30-04-2009',
						'status' => 'Tidak Aktif',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'2' => array(
						'nolesen' => 'TG0002',
						'namapp' => 'Wan Ibrahim Bin Wan Mansor',
						'jenis' => 'Nature Guide (T3)',
						'tarikh' => '02-09-2009',
						'status' => 'Aktif',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='".SYSTEM_URL."/tg/tg/batalulasan'><img src='".IMAGES_PATH."icon/del.png' title='Batal Lesen'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					
					'3' => array(
						'nolesen' => 'TG0004',
						'namapp' => 'Khairul Bin Ariffin',
						'jenis' => 'City Guide',
						'tarikh' => '22-08-2009',
						'status' => 'Aktif',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'4' => array(
						'nolesen' => 'TG0011',
						'namapp' => 'Ahmad Zulkarnain Bin Zulkifli',
						'jenis' => 'Nature Guide (T2)',
						'tarikh' => '12-04-2010',
						'status' => 'Aktif<br />(Kemaskini Kad/Sijil)',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='".SYSTEM_URL."/tg/tg/pulanglesen'><img src='".IMAGES_PATH."icon/edit.png' title='Pemulangan Lesen'></a>&nbsp;
										<a href='".SYSTEM_URL."/tg/tg/kadganti'><img src='".IMAGES_PATH."icon/edit.png' title='Serahan Kad Baru'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'5' => array(
						'nolesen' => 'TG0012',
						'namapp' => 'Hajar Binti Hamdan',
						'jenis' => 'Nature Guide (T3)',
						'tarikh' => '15-10-2009',
						'status' => 'Aktif<br />(Penggantian Kad)',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='".SYSTEM_URL."/tg/tg/kadganti'><img src='".IMAGES_PATH."icon/edit.png' title='Serahan Kad Baru'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'6' => array(
						'nolesen' => 'TG0013',
						'namapp' => 'Muhammad Bin Ahmad',
						'jenis' => 'City Guide',
						'tarikh' => '25-04-2009',
						'status' => 'Aktif<br />(Pembaharuan Lesen)',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='".SYSTEM_URL."/tg/tg/pulanglesen'><img src='".IMAGES_PATH."icon/edit.png' title='Pemulangan Lesen'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					),
					'7' => array(
						'nolesen' => 'TG0014',
						'namapp' => 'Tee Tong Tong',
						'jenis' => 'City Guide',
						'tarikh' => '19-12-2009',
						'status' => 'Aktif<br />(Pembaharuan Lesen)',
						'aktiviti' => "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
										<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>",
					)
				);

?>
<input type="hidden" name="inputId" id="inputId">
<table id="unijaya" width="100%"  align="center" cellspacing="1" >
	<tr>
		<th width="5%" align="center">Bil</th>
		<th width="10%"><a href='#'>No Lesen</a></th>
		<th width="25%"><a href='#'>Nama Pemandu Pelancong</a></th>
		<th width="15%"><a href='#'>Jenis</a></th>
		<th width="15%"><a href='#'>Tarikh Tamat Lesen</a></th>
		<th width="15%"><a href='#'>Status</a></th>
		<th width="15%">Aktiviti</th>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="subtitulo" ><input
								type="text" 
								onchange="changeFilters('filter_usr_id,filter_usr_fullname,filter_usr_identno,filter_usr_email,','/prototype/DOF/eLesen/admin/user/list');" id="filter_usr_id"   
								class="input-text required-entry" 
								value=""  style="width:95%"  ></td>
		<td class="subtitulo" ><input 
								type="text" 
								onchange="changeFilters('filter_usr_id,filter_usr_fullname,filter_usr_identno,filter_usr_email,','/prototype/DOF/eLesen/admin/user/list');" id="filter_usr_fullname"   
								class="input-text required-entry" 
								value=""  
								style="width:95%"  ></td>
		<td class="subtitulo" ><input 
								type="text" 
								onchange="changeFilters('filter_usr_id,filter_usr_fullname,filter_usr_identno,filter_usr_email,','/prototype/DOF/eLesen/admin/user/list');" id="filter_usr_identno"   
								class="input-text required-entry" 
								value=""  
								style="width:95%"  ></td>
		<td class="subtitulo" ><input 
								type="text" 
								onchange="changeFilters('filter_usr_id,filter_usr_fullname,filter_usr_identno,filter_usr_email,','/prototype/DOF/eLesen/admin/user/list');" id="filter_usr_identno"   
								class="input-text required-entry" 
								value=""  
								style="width:95%"  ></td>
		<td class="subtitulo" ><input 
								type="text" 
								onchange="changeFilters('filter_usr_id,filter_usr_fullname,filter_usr_identno,filter_usr_email,','/prototype/DOF/eLesen/admin/user/list');" id="filter_usr_identno"   
								class="input-text required-entry" 
								value=""  
								style="width:95%"  ></td>
		<td>&nbsp;</td>
	</tr>
	<?php
		$int_counter = 0;
		/*
		$xtvt = "<a href='#'><img src='".IMAGES_PATH."icon/view.png' title='Papar'></a>&nbsp;
				<a href='#'><img src='".IMAGES_PATH."icon/print.gif' title='Cetak'></a>";
		*/
		
		/*
		foreach ($arr_senarai as $key => $value){
			//print_r($value);
			$int_counter++;
			echo "<tr>";
			echo "<td align='center' valign='top' ".(($key == 0 || $key == 2)?"class=\"contents_warning_2_no\"":"").">".$int_counter."</td>";
			foreach($value as $detail){
				echo "<td valign='top' ".(($key == 0 || $key == 2)?"class=\"contents_warning_2\"":"").">$detail</td>";
			}
			//echo "<td>".$xtvt."</td>";
			echo "</tr>";
		}
		*/
		
		foreach ($arr_senarai as $key => $value){
			//print_r($value);
			$int_counter++;
			echo "<tr>";
			
			echo "<td align='center' valign='top' ";
			
			if($key == 2)
				echo "class='contents_warning_2_no'";
			elseif($key == 3)
				echo "class='contents_warning_3_no'";
			else
				echo "";
			
			echo ">".$int_counter."</td>";
			
			foreach($value as $detail){
				echo "<td valign='top' ";
			
				if($key == 2)
					echo "class='contents_warning_2'";
				elseif($key == 3)
					echo "class='contents_warning_3'";
				else
					echo "";
				
				echo ">".$detail."</td>";
			}
			echo "</tr>";
		}		
	?>
	<tr>
		<td class="barra_tabela" colspan="7">
			<div style="padding:2px;">
				<div style="float:left;width:30%;">
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/pdf'><img title="PDF"  src="<?= IMAGES_PATH ?>icon/pdf.gif"  border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/word'><img title="Microsoft Office 2003" src="<?= IMAGES_PATH ?>icon/word.gif"  border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/wordx'><img title="Microsoft Office 2007" src="<?= IMAGES_PATH ?>icon/wordx.gif"  border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/excel'><img title="Microsoft Excel"  src="<?= IMAGES_PATH ?>icon/excel.gif"  border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/print'><img src="<?= IMAGES_PATH ?>icon/print.gif" border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/xml'><img src="<?= IMAGES_PATH ?>icon/xml.gif" border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/csv'><img src="<?= IMAGES_PATH ?>icon/csv.gif" border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/ods'><img title="OpenOffice Spreadsheet" src="<?= IMAGES_PATH ?>icon/ods.gif" border="0"></a>
					<a target='_blank' href='/prototype/DOF/eLesen/admin/user/list/export/odt'><img title="OpenOffice Document Text" src="<?= IMAGES_PATH ?>icon/odt.gif"  border="0"></a>
				</div>
				<div style="float:left;text-align:center;width:50%;"> <em>(1 hingga <?= count($arr_senarai); ?> dari <?= count($arr_senarai); ?>)</em>  | </div>
				<div style="float:right;width:20%;"></div>
			</div>
        </td>
	</tr>
</table>