<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<!--
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Pautan PPP') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/permohonan" target="right"><?= $this->translate->_('Permohonan Baru') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/pengkelasan" target="right"><?= $this->translate->_('Permohonan Pengkelasan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/senarai" target="right"><?= $this->translate->_('Senarai PPP') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/info" target="right"><?= $this->translate->_('Info PPP') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/rating" target="right"><?= $this->translate->_('Star Rating') ?></a></li>
						</ul>
					</div>
				</div>
				-->
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Pemandu Pelancong') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/transaksilist" target="right"><?= $this->translate->_('Transaksi Permohonan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/applynew" target="right"><?= $this->translate->_('Permohonan Lesen Baru') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/rayuan" target="right"><?= $this->translate->_('Permohonan Rayuan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/list" target="right"><?= $this->translate->_('Senarai Lesen') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/newappllist" target="right"><?= $this->translate->_('Senarai Permohonan Lesen') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/renewlist" target="right"><?= $this->translate->_('Senarai Pembaharuan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/cancellist" target="right"><?= $this->translate->_('Senarai Pembatalan') ?></a></li>
							<!--
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/cancellist" target="right"><?= $this->translate->_('Senarai Kemaskini') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/cancellist" target="right"><?= $this->translate->_('Senarai Penggantian Kad/Sijil') ?></a></li>
							-->
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/kompaunlist" target="right"><?= $this->translate->_('Senarai Kompaun') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/tg/tg/rayuanlist" target="right"><?= $this->translate->_('Senarai Rayuan') ?></a></li>
						</ul>
					</div>
				</div>
			</div>
			<br>
			<div class="entry-edit" style="margin-left:20px;height:29px;width:210px;text-align:center">
				<div class="fieldset" id="group_fields63" style="background-color:AntiqueWhite;">
					<span id="clock" valign="middle"></span>
				</div>
			</div>
			<br>
			<div style="height: 150px; background: url('<?= IMAGES_PATH ?>tpl/banner2/left_menu_spip.jpg') no-repeat">
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			</div>
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>