		<?php if($this->failedValidation): ?>
			<p class="error">Terdapat masalah semasa kemaskini kata laluan.</p> 
		<?php elseif($this->oldpasswordError): ?>
			<p class="error"><?= $this->translate->_('Kata Laluan lama tidak sah! Sila cuba sekali lagi.') ?></p>
		<?php elseif($this->newpasswordError): ?>
			<p class="error"><?= $this->translate->_('Kata Laluan Baru dan Kata Laluan Baru (Semula) tidak sama! Sila cuba sekali lagi.') ?></p>
		<?php endif; ?>


		<?php if($this->profilSaved): ?>
			<p class="success">Kemaskini kata laluan berjaya</p>
			<meta http-equiv="refresh" content=1;URL="password">
		<?php else: ?>
		
	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Kemaskini Kata Laluan</h3></td>
		    </tr>
		</table>
	</div>
	<?php include('info.phtml'); ?>
	
	<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">
			
			<div class="entry-edit">
				<div class="fieldset">
					<p class="box">Anda boleh menukar kata laluan anda pada ruangan di bawah ini.</p>
					<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
						<colgroup>
							<col class="oce-first" />
							<col>
						</colgroup>
						<tbody>
							<tr>
								<td width="20%">Kata Laluan Lama</td>
								<td><?= $this->form->oldpassword ?></td>
							</tr>
							<tr>
								<td width="20%">Kata Laluan Baru</td>
								<td><?= $this->form->newpassword1 ?></td>
							</tr>
							<tr>
								<td width="20%">Kata Laluan Baru (Semula)</td>
								<td><?= $this->form->newpassword2 ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		
			<br/>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="submit" class="scalable save" name="submit" id="submit" style=""><span>Kemaskini</span></button> &nbsp;
					<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
				</div>
			</div>
		</form>
		
		<?php endif; ?>