	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Profil Pengguna</h3></td>
		    </tr>
		</table>
	</div>
	<?php include('info.phtml'); ?>
<?php 
		/******Enable Dojo**********/
		$this->dojo()->enable(); 
		// Container with tabs
		$this->tabContainer()->captureStart('profiledit', array(), array('style' => 'width:100%;text-align:left;', 'doLayout'=>'false', 'tabPosition'=>'top')); 
			 // First tab "Am"
			$this->contentPane()->captureStart('general', array(), array('title' => $this->translate->_('Maklumat Peribadi')));
	?>

			<div class="entry-edit">
				<div class="fieldset " id="group_fields63">
					<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
						<colgroup>
							<col class="oce-first" />
							<col>
							<col class="oce-first" />
							<col>
						</colgroup>
						<tbody>
							<tr>
								<td width="20%">Nama</td>
								<td colspan="3"><?= isset($this->rowset->usr_fullname) ? strtoupper($this->rowset->usr_fullname) : 'TIADA MAKLUMAT'; ?></td>
							</tr> 
							<tr>
								<td>No MyKad</td>
								<td  colspan="3" width="30%"><?= isset($this->rowset->usr_identno) ? strtoupper($this->rowset->usr_identno) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>No Jabatan</td>
								<td colspan="3"><?= isset($this->rowset->jhev_no) ? strtoupper($this->rowset->jhev_no) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>Bahagian</td>
								<td><?= isset($this->rowset->jhev_dept) ? strtoupper($this->function->getDeptJhevById($this->rowset->jhev_dept)) : 'TIADA MAKLUMAT'; ?></td>
								<td>Unit</td>
								<td><?= isset($this->rowset->jhev_unit) ? strtoupper($this->function->getUnitJhevById($this->rowset->jhev_unit)) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							
							<tr>
								<td>Tarikh Lahir</td>
								<td width="30%"><?= isset($this->rowset->usr_date_birth) ? strtoupper($this->date->func_ymd2dmy2($this->rowset->usr_date_birth)) : 'TIADA MAKLUMAT'; ?></td>
								<td>Umur</td>
								<td width="30%"><?= isset($this->rowset->usr_date_birth) ? strtoupper(date('Y') - substr($this->rowset->usr_date_birth,0,4)) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td valign="top">Alamat Tetap</td>
								<td colspan="3"><?= isset($this->rowset->usr_add_primary) ? strtoupper($this->rowset->usr_add_primary) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>Poskod</td>
								<td><?= isset($this->rowset->usr_poscode_primary) ? strtoupper($this->rowset->usr_poscode_primary) : 'TIADA MAKLUMAT'; ?></td>
								<td>Bandar</td>
								<td><?= isset($this->rowset->usr_city_primary) ? strtoupper($this->rowset->usr_city_primary) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>Negeri</td>
								<td colspan="3"><?= isset($this->rowset->usr_state_primary) ? strtoupper($this->func->getStateById($this->rowset->usr_state_primary)) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							
							<tr>
								<td>Jantina</td>
								<td colspan="3"><?= isset($this->rowset->usr_sex) ? strtoupper($this->func->getSexById($this->rowset->usr_sex)) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>No Telefon (R)</td>
								<td><?= isset($this->rowset->usr_phone_no) ? strtoupper($this->rowset->usr_phone_no) : 'TIADA MAKLUMAT'; ?></td>
								<td>No Telefon (M)</td>
								<td><?= isset($this->rowset->usr_mobile_no) ? strtoupper($this->rowset->usr_mobile_no) : 'TIADA MAKLUMAT'; ?></td>
							</tr>
							<tr>
								<td>Emel</td>
								<td colspan="3"><?= $this->rowset->usr_email ?></td>
							</tr>
						</tbody>
					</table>
				</div>	
			</div>
	<?php
		echo $this->contentPane()->captureEnd('general');
		/**************End Tab 1******************/
		//Tab 2 "pengalaman"
	?>
	
	
	<?php
		echo $this->tabContainer()->captureEnd('profiledit'); 
		/**************End Container******************/
	?>
			<br/>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
				</div>
			</div>
