<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Penyata Pencen') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_penyata', 'tahun2010'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/tahun2011" target="right">'. $this->translate->_('Penyata Tahun 2011') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_penyata', 'tahun2012'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/tahun2012/x/2012" target="right">'. $this->translate->_('Penyata Tahun 2012') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_penyata', 'tahun2012'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/tahun2012/x/2013" target="right">'. $this->translate->_('Penyata Semasa 2013') .'</a></li>';
								//if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_penyata', 'tahun2009'))
								//	echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/tahun2009" target="right">'. $this->translate->_('Penyata Tahun 2009') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_penyata', 'carian'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/carian" target="right">'. $this->translate->_('Carian') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Bantuan') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								//if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/penyata/bantuan" target="right">'. $this->translate->_('Manual Pengguna') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
			</div>
			
			<br>
			<br>
			
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>