<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="400" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Pautan ACL') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								/* if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2){
									echo '<li><a href="'. SYSTEM_URL .'/admin/acl/module" target="right">Module</a></li>';
									echo '<li><a href="'.SYSTEM_URL .'/admin/acl/resources" target="right">Resource</a></li>'; */
							?>
							<li><a href="<?= SYSTEM_URL ?>/admin/acl/module" target="right">Module</a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/acl/resources" target="right">Resource</a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/acl/privileges" target="right">Privilege</a></li>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Pautan Pengguna') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/admin/staff" target="right"><?= $this->translate->_('Senarai Kakitangan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/user" target="right"><?= $this->translate->_('Senarai Pengguna') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/group" target="right"><?= $this->translate->_('Senarai Kumpulan Pengguna') ?></a></li>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Pautan Penyelenggaraan') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/admin/information" target="right"><?= $this->translate->_('Informasi Sistem') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/db" target="right"><?= $this->translate->_('DB Backup & Restore') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/auditrail" target="right"><?= $this->translate->_('Jejak Audit') ?></a></li>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Pautan Induk') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/admin/unitbpm" target="right"><?= $this->translate->_('Unit BPM') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/masalah" target="right"><?= $this->translate->_('Kategori Masalah') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/bahagian" target="right"><?= $this->translate->_('Bahagian') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/admin/unit" target="right"><?= $this->translate->_('Unit') ?></a></li>
						</ul>
					</div>
				</div>
			</div>
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>