<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Profil Peribadi') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_personal', 'profile'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/personal/profile" target="right">'. $this->translate->_('Profil') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_personal', 'profileedit'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/personal/profileedit" target="right">'. $this->translate->_('Kemaskini Profil') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_personal', 'fotoedit'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/personal/fotoedit" target="right">'. $this->translate->_('Foto') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bp_personal', 'password'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/personal/password" target="right">'. $this->translate->_('Tukar Kata Laluan') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Bantuan') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								//if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bp/personal/bantuan" target="right">'. $this->translate->_('Manual Pengguna') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
			</div>
			
			<br>
			<br>
			
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>