<div class="content-header">
	<table cellspacing="0">
	    <tr>
	        <td style="width:50%;"><h3 class="icon-head head-customer">Surat Khabar Utama</h3></td>
	    </tr>
	</table>
</div>
<div class="entry-edit">
	<div class="fieldset" id="group_fields63">
		<table cellpadding="5" cellspacing="1" width="100%" border="0">
			<tbody>
				<tr>
					<td width="25%"><a href="<?= SYSTEM_URL ?>/btm/paper/list/group/1"><img src="<?= IMAGES_PATH  ?>/paper/bharian.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/utusan.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/hmetro.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/kosmo.jpg"></a></td>
				</tr>
				<tr>
					<td colspan="4">&nbsp;</td>
				</tr>
				<tr>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/sinar.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/nst.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/the_star.jpg"></a></td>
					<td width="25%"><a href=""><img src="<?= IMAGES_PATH  ?>/paper/sun.jpg"></a></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>


