<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Kajian Kepuasan Pekerja') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/kajian/borang" target="right">'. $this->translate->_('Borang') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
				<div dojoType="dijit.layout.AccordionPane" title="<?= $this->translate->_('Laporan') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/jawatan" target="right">'. $this->translate->_('Kumpulan Jawatan') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/bahagian" target="right">'. $this->translate->_('Bahagian') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/jantina" target="right">'. $this->translate->_('Jantina') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/umur" target="right">'. $this->translate->_('Umur') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/perkhidmatan" target="right">'. $this->translate->_('Skala Mutu Perkhidmatan') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'bkp_kajian', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/bkp/report/cadangan" target="right">'. $this->translate->_('Komen / Cadangan') .'</a></li>';
							?>
						</ul>
					</div>
				</div>
			</div>
			
			<br>
			<br>
			
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>