<?php
	$arr_kronologi 	= array(
						'1' => array(
								'penerangan' => 'Aduan Baru',
								'nama' => 'Pembantu Tadbir (Zamarul Hisham)',
								'tarikhterima' => '25-05-2009 14:00:00',
								'tarikhselesai' => '25-05-2009 15:30:00',
								//'jangkamasa' => 'Tidak Lewat',
						),
						'2' => array(
								'penerangan' => 'Pengesahan Penyelia',
								'nama' => 'Pembantu Tadbir (Norman Hakim)',
								'tarikhterima' => '25-05-2009 15:30:00',
								'tarikhselesai' => '-',
								//'jangkamasa' => 'Tidak Lewat',
						),
						'3' => array(
								'penerangan' => 'Kelulusan Pegawai BPM',
								'nama' => '-',
								'tarikhterima' => '-',
								'tarikhselesai' => '-',
								//'jangkamasa' => '-',
						),
						'4' => array(
								'penerangan' => 'Tindakan Staf BPM',
								'nama' => '-',
								'tarikhterima' => '-',
								'tarikhselesai' => '-',
								//'jangkamasa' => '-',
						),
					);
?>
	<div class="entry-edit">
		<div class="fieldset " id="group_fields63">
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="100%">
				<colgroup>
					<col class="oce-first" />
					<col />
					<col class="oce-first" />
					<col />
				</colgroup>
				<tbody>
					<tr>
						<td height="40px" colspan="4" class="title" style="text-align:center;"><span style="font-size:18px;text-align:center"><strong><?= $this->translate->_('Kronologi Aduan') ?></strong></span>
						</td>
					</tr>
				</tbody>
			</table>
			<br />
			<div class="fieldset" id="group_fields63">
			<table width="100%" cellpadding="5" cellspacing="1">
				<tr>
					<td width="10%"><strong>Petunjuk:</strong></td>
					<td width="30px" style="border:solid 1px #000000"></td>
					<td width="20%" align="left" valign="top"> <nobr>Tidak Lewat</nobr></td>
					<td width="30px" class="contents_warning_2"></td>
					<td width="60%" align="left" valign="top"> <nobr>Lewat</nobr></td>
				</tr>
			</table>
			</div>
			<br/>
			<table cellpadding="0" cellspacing="0" width="100%">
				<tr align="center" valign="middle">
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td bgcolor="#CCCCCC"><div align="center"><strong>Permohonan<br>Baru</strong><br>25-05-2009<br>14:00:00</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
					<td>
						<img src="<?= IMAGES_PATH ?>corner/barrow_green.gif" height="30" width="40">
					</td>
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td  bgcolor="#CCCCCC"><div align="center"><strong>Semakan<br>Permohonan</strong><br>25-05-2008<br>15:00:00</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
					<td>
						<img src="<?= IMAGES_PATH ?>corner/barrow_green.gif" height="30" width="40">
					</td>
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td  bgcolor="#CCCCCC"><div align="center"><strong>Syor/Ulasan</strong><br>-</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
					<td>
						<img src="<?= IMAGES_PATH ?>corner/barrow_green.gif" height="30" width="40">
					</td>
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td  bgcolor="#CCCCCC"><div align="center"><strong>Perakuan</strong><br>-</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
					<td>
						<img src="<?= IMAGES_PATH ?>corner/barrow_green.gif" height="30" width="40">
					</td>
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td  bgcolor="#CCCCCC"><div align="center"><strong>Kelulusan</strong><br>-</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
					<td>
						<img src="<?= IMAGES_PATH ?>corner/barrow_green.gif" height="30" width="40">
					</td>
					<td>
						<table cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right.gif"></td>
							</tr>

							<tr>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td  bgcolor="#CCCCCC"><div align="center"><strong>Selesai</strong><br>-</div></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
							</tr>

							<tr>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_left_bottom.gif"></td>
								<td bgcolor="#CCCCCC"><!---null---></td>
								<td><img src="<?= IMAGES_PATH ?>corner/corner_right_bottom.gif"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<br/>
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="100%">
				<tbody>
					<tr>
						<td width="5%" align="center" class="oce-first" rowspan="2"><strong>Bil</strong></td>
						<td width="20%" align="center" class="oce-first" rowspan="2"><strong>Penerangan</strong></td>
						<td width="35%" align="center" class="oce-first" rowspan="2"><strong>Kumpulan Pengguna (Nama Pegawai)</strong></td>
						<td width="40%" align="center" class="oce-first" colspan="2"><strong>Tarikh (Masa)</strong></td>
						<!--<td width="15%" align="center" class="oce-first" rowspan="2"><strong>Jangka Masa</strong></td>-->
					</tr>
					<tr>
						<td width="20%" align="center" class="oce-first"><strong>Terima</strong></td>
						<td width="20%" align="center" class="oce-first"><strong>Selesai</strong></td>
					</tr>
					<?php
						foreach ($arr_kronologi as $key => $value)
						{
							echo "<tr ";
							if($key == 2)
								echo " class='contents_warning_2'";
							else
								echo "";
							echo ">";
							
							echo "	<td align='center' valign='top'>".$key."</td>";
							
							foreach($value as $detail)
								echo "<td valign='top'>".$detail."</td>";
							
							echo "</tr>";
						}
					?>
				</tbody>
			</table>	
		</div>	
