<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Surat Khabar') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<?php 	
								//if ($this->acl->isAllowed($this->role, 'admin_acl', 'index'))
								//if ($this->role == 2 || $this->acl->isAllowed($this->role, 'btm_paper', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/btm/paper/add" target="right">'. $this->translate->_('Tambah') .'</a></li>';
								//if ($this->role == 2 || $this->acl->isAllowed($this->role, 'btm_paper', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/btm/paper/list" target="right">'. $this->translate->_('Senarai Keratan') .'</a></li>';
								/* if ($this->role == 2 || $this->acl->isAllowed($this->role, 'btm_paper', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/btm/paper/new" target="right">'. $this->translate->_('Terbaru') .'</a></li>';
								if ($this->role == 2 || $this->acl->isAllowed($this->role, 'btm_paper', 'borang'))
									echo '<li><a href="'.SYSTEM_URL .'/btm/paper/glist" target="right">'. $this->translate->_('Surat Khabar Utama') .'</a></li>'; */
							?>
						</ul>
					</div>
				</div>
			</div>
			
			<br>
			<br>
			
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>