	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Bantuan - Profil</h3></td>
		    </tr>
		</table>
	</div>
	<br/>
	<div class="entry-edit" align="left">
		<div class="fieldset" id="group_fields63">
	<div>
	<b><span style="font-size: 16pt; line-height: 115%;">Modul Profil</span></b></div>
<div>
	Pada Menu sila klik Laman Profil. <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\menu_profil.jpg" height="26" src="<?= IMAGES_PATH ?>manual/menu_profil.jpg" width="57" /></div>
<div>
	Paparan laman <b>Profil </b>akan dipaparkan.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\profil.jpg" height="300" src="<?= IMAGES_PATH ?>manual/profil.jpg" width="627" /></div>
<div>
	&nbsp;</div>
<div>
	<b>Menu Profil</b></div>
<div>
	Di sebelah kiri paparan profil adalah menu untuk modul Profil.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\1.jpg" height="239" src="<?= IMAGES_PATH ?>manual/1.jpg" width="230" /></div>
<div>
	<b>Profil</b></div>
<div>
	Klik <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\profil1.jpg" height="20" src="<?= IMAGES_PATH ?>manual/profil1.jpg" width="83" />untuk ke paparan Profil yang memaparkan profil pengguna. Terdapat dua (2) tab iaitu Maklumat Peribadi dan Maklumat Perkhidmatan.</div>
<div>
	&nbsp;</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\2.jpg" height="401" src="<?= IMAGES_PATH ?>manual/2.jpg" width="626" /></div>
<div>
	Klik tab Maklumat Peribadi <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\maklumatperibadi.jpg" height="38" src="<?= IMAGES_PATH ?>manual/maklumatperibadi.jpg" width="131" /></div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\3.jpg" height="235" src="<?= IMAGES_PATH ?>manual/3.jpg" width="626" /></div>
<div>
	Klik tab Maklumat Perkhidmatan <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\maklumatperkhidmatan.jpg" height="38" src="<?= IMAGES_PATH ?>manual/maklumatperkhidmatan.jpg" width="168" /></div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\4.jpg" height="112" src="<?= IMAGES_PATH ?>manual/4.jpg" width="626" /></div>
<div>
	&nbsp;</div>
<div>
	<b>Kemaskini Profil</b></div>
<div>
	Klik <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\kemaskiniprofil.jpg" height="22" src="<?= IMAGES_PATH ?>manual/kemaskiniprofil.jpg" width="165" />untuk ke paparan Kemaskini Profil yang memaparkan halaman kemaskini profil pengguna. Di sini pengguna boleh mengemaskini maklumat peribadi dan perkhidmatan. Terdapat dua (2) tab iaitu Maklumat Peribadi dan Maklumat Perkhidmatan.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\5.jpg" height="457" src="<?= IMAGES_PATH ?>manual/5.jpg" width="627" /></div>
<div>
	Pengguna diperlukan untuk memberikan maklumat sebenar untuk kegunaan sistem ini. Sila isikan maklumat pada setiap ruangan. Ruangan bertanda <b><span style="color: red;">* </span></b>adalah diwajibkan untuk diisi. Setelah maklumat diisi, klik butang Kemaskini <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\kemaskini.jpg" height="32" src="<?= IMAGES_PATH ?>manual/kemaskini.jpg" width="111" />&nbsp;untuk mengemaskini maklumat yang telah dimasukkan.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\6.jpg" height="351" src="<?= IMAGES_PATH ?>manual/6.jpg" width="627" /></div>
<div>
	&nbsp;</div>
<div>
	<b>Kemaskini Foto</b></div>
<div>
	Klik <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\foto.jpg" height="26" src="<?= IMAGES_PATH ?>manual/foto.jpg" width="76" />untuk ke paparan Foto. Di sini pengguna digalakkan untuk memuat naik gambar bersaiz foto. Klik pada butang Browse <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\browse.jpg" height="31" src="<?= IMAGES_PATH ?>manual/browse.jpg" width="81" />&nbsp;untuk memilih gambar yang sesuai. Seterusnya klik butang Kemaskini <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\kemaskini.jpg" height="32" src="<?= IMAGES_PATH ?>manual/kemaskini.jpg" width="111" />untuk muatnaik gambar tersebut.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\7.jpg" height="243" src="<?= IMAGES_PATH ?>manual/7.jpg" width="627" /></div>
<div>
	&nbsp;</div>
<div>
	<b>Tukar Kata Laluan</b></div>
<div>
	Klik <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\tukarkatalaluan.jpg" height="25" src="<?= IMAGES_PATH ?>manual/tukarkatalaluan.jpg" width="135" />&nbsp;untuk ke paparan Tukar Kata Laluan. Di paparan ini, pengguna boleh mengemaskini kata laluan kepada kata laluan yang baru. Setelah mengisi maklumat yang diperlukan, klik butang Kemaskini <img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\kemaskini.jpg" height="32" src="<?= IMAGES_PATH ?>manual/kemaskini.jpg" width="111" />&nbsp;untuk proses pengemaskinian.</div>
<div>
	<img alt="Description: D:\OSC\jhevintra\gambar\manual eOnline\8.jpg" height="276" src="<?= IMAGES_PATH ?>manual/8.jpg" width="627" /></div>
	
		</div>
	</div>
	<div class="entry-edit">
		<div class="fieldset" style="text-align:center;">
			<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
		</div>
	</div>
