	<?php if($this->failedValidation): ?>
			<p class="error">Terdapat masalah semasa kemaskini maklumat perkhidmatan.</p> 
		<?php endif; ?>

		<?php if($this->profilSaved): ?>
			<p class="success">Kemaskini maklumat perkhidmatan berjaya</p>
			<meta http-equiv="refresh" content=1;URL="profile">
		<?php else: ?>
		
	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Kemaskini Foto</h3></td>
		    </tr>
		</table>
	</div>
	<?php include('info.phtml'); ?>
	
	<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>" enctype="multipart/form-data">
			

			<div class="entry-edit">
				<div class="fieldset " id="group_fields63">
					<p class="box">Tekan Browse untuk menukar gambar foto anda.</p>
					<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
						<colgroup>
							<col class="oce-first" />
							<col>
							<col class="oce-first" />
							<col>
						</colgroup>
						<tbody>
							<tr>
								<td width="20%">Foto</td>
								<td colspan="3"><input name="file" type="file" /></td>
							</tr> 
						</tbody>
					</table>
					<input type="hidden" name="file_upload" value="1" />
					<!--<button id="submit" name="submit" type="submit" dojoType="dijit.form.Button">Submit!</button>-->
					
				</div>	
			</div>
		
			<br/>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="submit" class="scalable save" name="submit" id="submit" style=""><span>Kemaskini</span></button>  
					<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
				</div>
			</div>
		</form>
		
		<?php endif; ?>