	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Profil Pengguna</h3></td>
		    </tr>
		</table>
	</div>
	<div class="entry-edit">
		<div class="fieldset" id="group_fields63">
			<table width="100%" border="0" cellpadding="5" cellspacing="1" bgcolor="#CCCCCC" id="info-box">
				<tr class="contents">
					<td height="25%" align="left" valign="top" bgcolor="#EFEFEF" class="head"><strong>Nama Pengguna</strong></td>
					<td align="left" valign="top" bgcolor="#FFFFFF" class="big-red"><?= Zend_Auth::getInstance()->getIdentity()->usr_id ?></td>
					
				</tr>
				<tr class="contents">
					<td width="25%" height="20" align="left" valign="top" bgcolor="#EFEFEF" class="head"><strong>No Kad Pengenalan</strong></td>
					<td align="left" valign="top" bgcolor="#FFFFFF" class="big-blue"><?= Zend_Auth::getInstance()->getIdentity()->usr_identno ?></td>
				</tr>
			</table>
		</div>
	</div>
<?php 
		/******Enable Dojo**********/
		$this->dojo()->enable(); 
		// Container with tabs
		$this->tabContainer()->captureStart('profiledit', array(), array('style' => 'width:100%;text-align:left;', 'doLayout'=>'false', 'tabPosition'=>'top')); 
			 // First tab "Am"
			$this->contentPane()->captureStart('general', array(), array('title' => $this->translate->_('Maklumat Peribadi'), 'selected' => ($this->tab == 'personal' ? 'true' : 'false')));
	?>
			<?php if($this->failedValidation): ?>
			<p class="error">Terdapat masalah semasa kemaskini maklumat peribadi.</p> 
		<?php endif; ?>

		<?php if($this->profilSaved): ?>
			<p class="success">Kemaskini maklumat peribadi berjaya</p>
			<meta http-equiv="refresh" content=1;URL="personal">
		<?php else: ?>

			<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">
			
			<div class="entry-edit">
				<div class="fieldset " id="group_fields63">
					<p class="box">Sila masukkan maklumat pada ruangan di bawah. <span class="required2">* Diperlukan</span></p>
					<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
						<colgroup>
							<col class="oce-first" />
							<col>
							<col class="oce-first" />
							<col>
						</colgroup>
						<tbody>
							<tr>
								<td width="20%">Nama&nbsp;<span class="required2">*</span></td>
								<td colspan="3"><?= $this->form->realname ?></td>
							</tr> 
							<tr>
								<td>Email&nbsp;<span class="required2">*</span></td>
								<td colspan="3"><?= $this->form->email ?></td>
							</tr>
							<tr>
								<td>Tarikh Lahir</td>
								<td width="30%"><?= $this->form->date_bday ?></td>
								<td>Umur</td>
								<td width="30%"><?= $this->form->age ?></td>
							</tr>
							<tr>
								<td>Agama</td>
								<td><?= $this->form->religion ?></td>
								<td>Jantina</td>
								<td><?= $this->form->gender ?></td>
							</tr>
							<tr>
								<td>Warganegara</td>
								<td><?= $this->form->nationality ?></td>
								<td>Status Perkahwinan</td>
								<td><?= $this->form->marital ?></td>
							</tr>
							<tr>
								<td>Pendidikan</td>
								<td colspan="3"><?= $this->form->education ?></td>
							</tr>
							<tr>
								<td valign="top">Alamat Rumah</td>
								<td colspan="3"><?= $this->form->address ?></td>
							</tr>
							<tr>
								<td>Poskod</td>
								<td><?= $this->form->poscode ?></td>
								<td>Bandar</td>
								<td><?= $this->form->city ?></td>
							</tr>
							<tr>
								<td>Negeri</td>
								<td><?= $this->form->state ?></td>
								<td>Negara</td>
								<td><?= $this->form->country ?></td>
							</tr>
							<tr>
								<td>No Telefon (R)</td>
								<td><?= $this->form->phone ?></td>
								<td>No Telefon (M)</td>
								<td><?= $this->form->mobile ?></td>
							</tr>
						</tbody>
					</table>
					<!--<button id="submit" name="submit" type="submit" dojoType="dijit.form.Button">Submit!</button>-->
					
				</div>	
			</div>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<?= $this->form->reset ?>&nbsp;
					<button type="submit" class="scalable save" name="submit" id="submit" style=""><span>Kemaskini</span></button>  
				</div>
			</div>
			</form>
		<?php endif; ?>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
						
				</div>
			</div>
		
	<?php
		echo $this->contentPane()->captureEnd('general');
		/**************End Tab 1******************/
		//Tab 2 "pengalaman"
	?>
	
	<?php
			/**************End Tab 5******************/
			//Tab 6 "Perakuan"
			$this->contentPane()->captureStart('bilik', array(), array('title' => $this->translate->_('Bilik Perbincangan/Mesyuarat/Dewan')));
			//echo "tab6 content";
	?>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="button" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
						
				</div>
			</div>
	
	<?php
			echo $this->contentPane()->captureEnd('bilik');
			/**************End Tab 6******************/
	?>
	<?php
			/**************End Tab 5******************/
			//Tab 6 "Perakuan"
			$this->contentPane()->captureStart('menu', array(), array('title' => $this->translate->_('Menu')));
			//echo "tab6 content";
	?>
			
			
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="button" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
						
				</div>
			</div>
	
	<?php
			echo $this->contentPane()->captureEnd('menu');
			/**************End Tab 6******************/
		echo $this->tabContainer()->captureEnd('profiledit'); 
		/**************End Container******************/
	?>