<?php if($this->failedValidation): ?>
    <p class="error"><?= $this->translate->_('Ada masalah') ?></p>
<?php endif; ?>

<?php if($this->entrySaved): ?>
    <p class="success"><?= $this->translate->_('Berjaya') ?></p>
    <meta http-equiv="refresh" content=1;URL="<?= SYSTEM_URL.'/btm/paper/list' ?>">
<?php else: ?>
<? //$this->form->name; ?>
<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>" enctype="multipart/form-data">
	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user"><?= $this->translate->_('Kemaskini Keratan Akhbar') ?></h3></td>
		    </tr>
		</table>
	</div>
	<div class="entry-edit">
		<div class="fieldset" id="group_fields63">
	    	<p class="box" align="left"><?= $this->translate->_('Masukkan maklumat pada ruangan di bawah.') ?></p>
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="100%">
				<colgroup>
					<col class="oce-first" />
				</colgroup>
				<tbody>
					<tr>
						<td width="25%"><?= $this->translate->_('Tajuk') ?></td>
						<td><?= $this->form->txt_tajuk ?></td>
					</tr>
					<tr>
						<td width="25%"><?= $this->translate->_('Keterangan') ?></td>
						<td><?= $this->form->txt_keterangan ?></td>
					</tr>
					<tr>
						<td width="25%"><?= $this->translate->_('Surat Khabar') ?></td>
						<td><?= $this->form->sel_paper ?></td>
					</tr>
					<tr>
						<td width="25%"><?= $this->translate->_('Kolum') ?></td>
						<td><?= $this->form->txt_kolum ?></td>
					</tr>
					<tr>
						<td width="25%"><?= $this->translate->_('Muka Surat') ?></td>
						<td><?= $this->form->txt_mukasurat ?></td>
					</tr>
					<tr>
						<td width="25%"><?= $this->translate->_('Gambar Keratan') ?></td>
						<td><img src="<?= SYSTEM_URL.'/upload/paper/'.$this->fail_gambar; ?>" width="40px"><br/><? //= $this->form->fail_gambar ?><input name="file" type="file" /></td>
					</tr>
				</tbody>
			</table>
			<input type="hidden" name="file_upload" value="1" />
			<br>
		</div>	
	</div>
	<div class="entry-edit">
		<div class="fieldset" style="text-align:center;">
			<button type="submit" class="scalable save" name="submit" id="submit"><span><?= $this->translate->_('Kemaskini') ?></span></button>&nbsp;
			<button type="reset" class="scalable reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Semula') ?></span></button>&nbsp;
			<button type="button" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
				
		</div>
	</div>
</form>
    <?php //print_r($this->soalan); ?>
<?php endif; ?>