<link rel="stylesheet" href="<?= JS_PATH ?>popup/general.css" type="text/css" media="all" />
<script src="<?= JS_PATH ?>jquery/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
/***************************/
//@Author: Adrian "yEnS" Mato Gondelle
//@website: www.yensdesign.com
//@email: yensamg@gmail.com
//@license: Feel free to use it, but keep this credits please!					
/***************************/

//SETTING UP OUR POPUP
//0 means disabled; 1 means enabled;
var popupStatus = 0;

//loading popup with jQuery magic!
function loadPopup(){
	//loads popup only if it is disabled
	if(popupStatus==0){
		$("#backgroundPopup").css({
			"opacity": "0.7"
		});
		$("#backgroundPopup").fadeIn("slow");
		$("#popupContact").fadeIn("slow");
		popupStatus = 1;
	}
}

//disabling popup with jQuery magic!
function disablePopup(){
	//disables popup only if it is enabled
	if(popupStatus==1){
		$("#backgroundPopup").fadeOut("slow");
		$("#popupContact").fadeOut("slow");
		popupStatus = 0;
	}
}

//centering popup
function centerPopup(){
	//request data for centering
	var windowWidth = document.documentElement.clientWidth;
	var windowHeight = document.documentElement.clientHeight;
	var popupHeight = $("#popupContact").height();
	var popupWidth = $("#popupContact").width();
	//centering
	$("#popupContact").css({
		"position": "absolute",
		"top": windowHeight/2-popupHeight/2,
		"left": windowWidth/2-popupWidth/2
	});
	//only need force for IE6
	
	$("#backgroundPopup").css({
		"height": windowHeight
	});
	
}


//CONTROLLING EVENTS IN jQuery
$(document).ready(function(){
	
	//LOADING POPUP
	//Click the button event!
	$("#buttonX").click(function(){
		//centering with css
		centerPopup();
		//load popup
		loadPopup();
	});
				
	//CLOSING POPUP
	//Click the x event!
	$("#popupContactClose").click(function(){
		disablePopup();
	});
	//Click out event!
	$("#backgroundPopup").click(function(){
		disablePopup();
	});
	//Press Escape event!
	$(document).keypress(function(e){
		if(e.keyCode==27 && popupStatus==1){
			disablePopup();
		}
	});

});
</script>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td style="width:50%;"><h3 class="icon-head head-user"><?= $this->translate->_('Papar Keratan Akhbar') ?></h3></td>
		</tr>
	</table>
</div>
<div class="entry-edit">
	<div class="fieldset" id="group_fields63">
		<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="100%">
			<colgroup>
				<col class="oce-first" />
			</colgroup>
			<tbody>
				<tr>
					<td width="25%"><?= $this->translate->_('Tajuk') ?></td>
					<td><?= $this->row['paper_name'] ?></td>
				</tr>
				<tr>
					<td width="25%"><?= $this->translate->_('Keterangan') ?></td>
					<td><?= nl2br($this->row['paper_desc']) ?></td>
				</tr>
				<tr>
					<td width="25%"><?= $this->translate->_('Surat Khabar') ?></td>
					<td><?= $this->row['p_group_name'] ?></td>
				</tr>
				<tr>
					<td width="25%"><?= $this->translate->_('Kolum') ?></td>
					<td><?= $this->row['paper_kolum'] ?></td>
				</tr>
				<tr>
					<td width="25%"><?= $this->translate->_('Muka Surat') ?></td>
					<td><?= $this->row['paper_mukasurat'] ?> <?= $this->row['paper_url'] ?></td>
				</tr>
				<tr>
					<td width="25%"><?= $this->translate->_('Gambar Keratan') ?></td>
					<td><p><a href="<?= SYSTEM_URL.'/'.$this->row['paper_url'] ?>" rel="thumbnail"><img src="<?php echo IMAGES_PATH.'/tpl/icons/preview.gif' ?>"/></a></p>
					</td>
				</tr>
			</tbody>
		</table>
		<br>
	</div>	
</div>
