<script language="Javascript" src="<?= system_path."/library/report/FusionCharts/FusionCharts.js"; ?>"></script>
<form name="frm_name" id="frm_name" method="post" action="<?= Zend_Controller_Front::getInstance()->getBaseUrl()."/bkp/report/jawatan"?>">
	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user"><?= $this->translate->_('Laporan Maklumbalas Mengikut Kumpulan Jawatan') ?></h3></td>
		        <td class="a-right">
		            <button type="button" class="scalable back" onclick="Javascript:history.back();" style=""><span><?= $this->translate->_('Kembali') ?></span></button>
	                <button type="reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Semula') ?></span></button>  
	                <button type="submit" class="scalable save" name="submit" id="submit" style=""><span><?= $this->translate->_('Hantar') ?></span></button>  
	                
	            </td>
		    </tr>
		</table>
	</div>
	<table class="contents" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr class="contents">
		<td valign="top" class="label" width="20%">Jenis</td>
		<td width="70%">
			<select name="select_jenis[]" size="6" multiple="multiple" id="select_jenis" >
            <?php 
				foreach($this->kump as $key => $kump){
					echo  "<option value=\"".$key."\" \>"
						.$kump
						."</option>";
				}
?>
        </select>
		</td>
	</tr>
	</table>
	<br />
</form>
