<script language="JavaScript">
var gAutoPrint = true; // Flag for whether or not to automatically call the print function

function printSpecial()
{

document.getElementById("logo").style.display = "";

if (document.getElementById != null)
{
var html = '<HTML>\n<HEAD>\n';

if (document.getElementsByTagName != null)
{
var headTags = document.getElementsByTagName("head");
if (headTags.length > 0)
html += headTags[0].innerHTML;
}

html += '\n</HE' + 'AD>\n<BODY>\n';

var printReadyElem = document.getElementById("printReady");

if (printReadyElem != null)
{
html += printReadyElem.innerHTML;
}
else
{
alert("Could not find the printReady section in the HTML");
return;
}

html += '\n</BO' + 'DY>\n</HT' + 'ML>';

var printWin = window.open("","printSpecial");
printWin.document.open();
printWin.document.write(html);
printWin.document.close();
if (gAutoPrint){
	printWin.print();
	document.getElementById("logo").style.display = "none";
	}
}
else
{
alert("Sorry, the print ready feature is only available in modern browsers.");
}
}



</script>
<div id="printReady">
	<div align="center" id="logo" style="display:none">
		<table border="0">
			<tr>
				<td><img src="<?= IMAGES_PATH ?>/jhev.png" width="70px"></td>
				<td>LAPORAN KEPUASAN PEKERJA JHEV TAHUN 2009</td>
			</tr>
		</table>
		
	</div>
<table cellpadding="5" cellspacing="1"  id="unijaya" width="100%">
	<colgroup>
		<col />
		<col class="oce-first" />
	</colgroup>
	<tbody>
		<tr>
			<th rowspan="2" width="6%"><?= $this->translate->_('Bil') ?></th>
			<th rowspan="2" width="20%"><?= $this->translate->_('Perkhidmatan') ?></th>
			<th colspan="10"><?= $this->translate->_('Skala') ?></th>
		</tr>
		<tr>
			<th width="5%"><?= $this->translate->_('1') ?></th>
			<th width="5%"><?= $this->translate->_('%') ?></th>
			<th width="5%"><?= $this->translate->_('2') ?></th>
			<th width="5%"><?= $this->translate->_('%') ?></th>
			<th width="5%"><?= $this->translate->_('3') ?></th>
			<th width="5%"><?= $this->translate->_('%') ?></th>
			<th width="5%"><?= $this->translate->_('4') ?></th>
			<th width="5%"><?= $this->translate->_('%') ?></th>
			<th width="5%"><?= $this->translate->_('5') ?></th>
			<th width="5%"><?= $this->translate->_('%') ?></th>
		</tr>
		<?php
			
			$arr_jum = array();
			
				
			foreach($this->result as $id=>$key){
				
				$strQuery = "SELECT 
								COUNT(*) AS jumlah 
							 FROM 
								tbl_jawapan
							 WHERE soalan_id = '".$id."'";
				
				$all = $this->db->fetchRow($strQuery);
				
				$jum_in = $all['jumlah'];
				//print_r($a);
		?>
		<tr>
			<td><?= $id ?></td>
			<td><?= $key ?></td>
			
			<?php
				
				for($i=1;$i<=5;$i++){
					
					$strQuery = "SELECT 
									COUNT(*) AS jumlah 
								 FROM 
									tbl_jawapan 
								 WHERE soalan_id = '".$id."'
								 AND skala = ".$i;
					
					$a = $this->db->fetchRow($strQuery);
					
					echo '<td>'.$a['jumlah'].'</td>';
					echo '<td>'.round(($a['jumlah']/$all['jumlah'])*100,2).'</td>';
					
					$arr_jum[$i][$id] = $a['jumlah'];
				
				}
			
			?>
			
			<!--<td><?= $a['jumlah'] ?></td>
			<td><?= round(($a['jumlah']/$all['jumlah'])*100,2) ?>%</td>-->
		</tr>
		
		<?php
			}
		?>
		<tr>
			<td colspan="2" align="center"><strong>Jumlah</strong></td>
		<?php
			
			for($i=1;$i<6;$i++){
				$jum = 0;
				for($j=1;$j<6;$j++){
					$jum += $arr_jum[$i][$j];
					
				}
				echo '<td><strong>'. $jum .'</strong></td>';
				echo '<td><strong>'. round(($jum/($jum_in*6))*100,2) .'</strong></td>';
			}
		?>
		
			
			
		</tr>

	</tbody>
</table>
</div>
<a href="javascript:void(printSpecial())">Print</a>
