<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 180px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('Pautan Pemohon') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/lesen/permohonan/applynew" target="right"><?= $this->translate->_('Permohonan Baru') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/lesen/permohonan/applylist" target="right"><?= $this->translate->_('Senarai Permohonan') ?></a></li>
						</ul>
					</div>
				</div>
			</div>
			<br>
			<div class="entry-edit" style="margin-left:20px;height:29px;width:210px;text-align:center">
				<div class="fieldset" id="group_fields63" style="background-color:AntiqueWhite;">
					<span id="clock" valign="middle"></span>
				</div>
			</div>
			<br>
			<div style="height: 150px; background: url('<?= IMAGES_PATH ?>tpl/banner2/left_menu_spip.jpg') no-repeat">
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			</div>
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>