<?php if($this->failedValidation): ?>
    <p class="error"><?= $this->translate->_('Terdapat masalah semasa pendaftaran pengguna baru') ?></p>
<?php elseif($this->emailError): ?>
    <p class="error"><?= $this->translate->_('Harap Maaf!!! Alamat emel yang dimasukkan tidak berdaftar dengan sistem ini.') ?></p>
<?php endif; ?>

<?php if($this->entrySaved): ?>
    <p class="success">
		<?= $this->translate->_('Emel telah berjaya dihantar.') ?>
		<br/>
		<?= $this->translate->_('Sila klik <a href="'.SYSTEM_URL.'/authentication/login" target="right">di sini</a> untuk ke halaman Daftar Masuk.') ?>
	</p>
<?php else: ?>

<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">
	<center>
	<div class="content-header" style="width:70%;">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user"><?= $this->translate->_('Forgot Password') ?></h3></td>
		    </tr>
		</table>
	</div>
	
	<div class="entry-edit" style="width:70%;">
		<div class="fieldset" style="text-align:center;">
	    	
			<p class="box"><?= $this->translate->_('Sila masukkan alamat emel yang digunakan untuk daftar masuk ke dalam sistem.') ?></p>
			
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" style="width:100%;">
				<colgroup>
					<col class="oce-first" />
				</colgroup>
				<tbody>
					<tr>
						<td width="25%"><?= $this->translate->_('Email') ?></td>
						<td><?= $this->form->txt_email ?></td>
					</tr>
				</tbody>
			</table>
			
		</div>	
	</div>
	
	<div class="entry-edit" style="width:70%;">
		<div class="fieldset" style="text-align:center;">
			<button type="submit" class="scalable save" name="submit" id="submit" style=""><span><?= $this->translate->_('Send') ?></span></button>  
			<button type="reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Reset') ?></span></button>  
			<button type="button" class="scalable back" onclick="Javascript:history.back();" style=""><span><?= $this->translate->_('Back') ?></span></button>
			</table>
		</div>
	</div>
	</center>
</form>
    
<?php endif; ?>