<SCRIPT language="javascript">
	var element1 = new dijit.form.TextBox({id : 'mobilephone_no', name : 'mobilephone_no'});

	function toggleMobileNo(element)   
	{	var phone = document.getElementById('mobile_no').value;
		if(phone.substring(0,2) != "01")
		{	
			if(document.getElementById('issms').value == "false")
			{	document.getElementById('issms').value = "true";
				document.getElementById('mobilenorow').insertCell(0).innerHTML="No Telefon Bimbit";
				document.getElementById('mobilenorow').insertCell(1).appendChild(element1.domNode); 
			}
			else
			{	document.getElementById('mobilenorow').deleteCell(1);
				document.getElementById('mobilenorow').deleteCell(0);
				document.getElementById('issms').value = "false";
			}
		}
	} 
</SCRIPT>  
<?php if($this->failedValidation): ?>
    <p class="error"><?= $this->translate->_('Terdapat masalah semasa pendaftaran pengguna baru') ?></p>
<?php elseif($this->userError): ?>
    <p class="error"><?= $this->translate->_('ID Pengguna yang dipilih sudah terdapat di dalam pangkalan data') ?></p> 
<?php elseif($this->nokpError): ?>
    <p class="error"><?= $this->translate->_('No KP yang dipilih sudah terdapat di dalam pangkalan data') ?></p> 
<?php elseif($this->emailError): ?>
    <p class="error"><?= $this->translate->_('Alamat Email yang dipilih sudah terdapat di dalam pangkalan data') ?></p> 
<?php endif; ?>

<?php if($this->entrySaved): ?>
    <p class="success"><?= $this->translate->_('Pendaftaran pengguna baru berjaya') ?></p>
    <meta http-equiv="refresh" content=1;URL="login">
<?php else: ?>
<center>
<div style="width:70%;">
<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">
	<div class="content-header">
		<table cellspacing="0" width="70%">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user"><?= $this->translate->_('Pendaftaran Pengguna') ?></h3></td>
		        <td class="a-right">
		            <button type="button" class="scalable back" onclick="Javascript:history.back();" style=""><span><?= $this->translate->_('Kembali') ?></span></button>
	                <button type="reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Semula') ?></span></button>  
	                <button type="submit" class="scalable save" name="submit" id="submit" style=""><span><?= $this->translate->_('Simpan') ?></span></button>  
	                
	            </td>
		    </tr>
		</table>
	</div>
	<div class="entry-edit">
		<div class="fieldset" id="group_fields63">
	    	<p class="box"><?= $this->translate->_('Sila masukkan maklumat pada ruangan di bawah.') ?> <span class="required2">* <?= $this->translate->_('Diperlukan') ?></span></p>
			<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="70%" name="regtable">
				<colgroup>
					<col class="oce-first" />
				</colgroup>
				<tbody>
					<tr>
						<td width="25%"><?= $this->translate->_('ID Pengguna') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_id ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Kata Laluan') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_password1 ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Kata Laluan (Semula)') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_password2 ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Nama') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_name ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('No Kad Pengenalan') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_identno ?>&nbsp;&nbsp;Contoh : <strong>860610355627 / A8481744</strong></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('No Jabatan') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_nojabatan ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Bahagian') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->jhev_dept ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Unit') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->jhev_unit ?></td>
					</tr>
					<tr>
						<td valign="top"><?= $this->translate->_('Alamat') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->primary_add ?></td>
						
					</tr>
					
					<tr>
						<td valign="top"><?= $this->translate->_('Poskod') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->poskod_add ?></td>
						
					</tr>
					
					<tr>
						<td valign="top"><?= $this->translate->_('Negeri') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->state_add ?></td>
					</tr>
					<tr>
						<td valign="top"><?= $this->translate->_('Bandar') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->district_add ?></td>
					</tr>
					
					<tr>
						<td><?= $this->translate->_('No Telefon Pejabat') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->office_no ?>&nbsp;&nbsp;Contoh : <strong>0320508000</strong></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('No Telefon Bimbit') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->mobile_no ?>&nbsp;&nbsp;Contoh : <strong>0121234567</strong></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Emel') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_email ?>&nbsp;&nbsp;Contoh : <strong>jhev@mod.gov.my</strong></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Jantina') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->user_sex ?></td>
					</tr>
					<tr>
						<td><?= $this->translate->_('Kumpulan Pengguna') ?>&nbsp;<span class="required2">*</span></td>
						<td><?= $this->form->group_id ?></td>
					</tr>
					<!--<tr>
						<td valign="top"><?= $this->translate->_('Kod Pengesahan') ?>&nbsp;<span class="required2">*</span></td>
						<td><? //= $this->form->captcha ?></td>
					</tr>-->
				</tbody>
			</table>
		</div>	
	</div>
	<div class="entry-edit">
		<div class="fieldset" style="text-align:center;" >
			<button type="submit" class="scalable save" name="submit" id="submit" style=""><span><?= $this->translate->_('Simpan') ?></span></button>  
			<button type="reset" name="reset" id="reset" style=""><span><?= $this->translate->_('Semula') ?></span></button>  
			<button type="button" class="scalable back" onclick="Javascript:history.back();" style=""><span><?= $this->translate->_('Kembali') ?></span></button>
			</table>
		</div>
	</div>

</form>
</div>

<?php endif; ?></center>