		<?php if($this->failedValidation): ?>
			<p class="error">Terdapat masalah semasa penghantaran maklumbalas.</p> 
		<?php endif; ?>


		<?php if($this->profilSaved): ?>
			<p class="success">Maklumbalas telah berjaya dihantar. Terima Kasih.</p>
			<meta http-equiv="refresh" content=1;URL="password">
		<?php else: ?>
		
	<div class="content-header">
		<table cellspacing="0">
		    <tr>
		        <td style="width:50%;"><h3 class="icon-head head-user-edit">Tambah Maklumbalas</h3></td>
		    </tr>
		</table>
	</div>
	<?php include('info.phtml'); ?>
	
	<form action="<?= $this->escape($this->form->getAction()) ?>" method="<?= $this->escape($this->form->getMethod()) ?>">
			
			<div class="entry-edit">
				<div class="fieldset">
					<p class="box">Sila isikan cadangan atau aduan anda di ruangan di bawah.</p>
					<table cellpadding="5" cellspacing="1"  id="one-column-emphasis" width="98%">
						<colgroup>
							<col class="oce-first" />
							<col>
						</colgroup>
						<tbody>
							<tr>
								<td width="20%">Cadangan / Aduan</td>
								<td><?= $this->form->feedback ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		
			<br/>
			<div class="entry-edit">
				<div class="fieldset" style="text-align:center;">
					<button type="submit" class="scalable save" name="submit" id="submit" style=""><span>Hantar</span></button> &nbsp;
					<button type="submit" class="scalable back" name="submit" id="submit" style="" onClick="Javascript:history.back();"><span><?= $this->translate->_('Kembali') ?></span></button>  
				</div>
			</div>
		</form>
		
		<?php endif; ?>