<style type="text/css">
	@import "<?= SYSTEM_URL ?>/public/dojo/dijit/themes/tundra/tundra.css";
	@import "<?= SYSTEM_URL ?>/public/dojo/dojo/resources/dojo.css"
</style>
<script type="text/javascript" src="<?= SYSTEM_URL ?>/public/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
	dojo.require("dojo.parser");
	dojo.require("dijit.layout.AccordionContainer");
</script>
<link href="<?= CSS_PATH ?>red.css" rel="stylesheet" type="text/css"/>
<table width="100%" height="95%" border="0">
	<tr>
		<td valign="top" align="left">
			<div dojoType="dijit.layout.AccordionContainer" duration="200" style="margin-left: 20px; width: 210px; height: 220px; overflow: hidden">
				<div dojoType="dijit.layout.AccordionPane" selected="true" title="<?= $this->translate->_('PPP') ?>">
					<div class="arrowlistmenu">
						<ul class="categoryitems">
							<li><a href="<?= SYSTEM_URL ?>/ppp/premise" target="right"><?= $this->translate->_('Senarai Premis') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/ppp/senaraipermohonan" target="right"><?= $this->translate->_('Senarai Permohonan') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/classification" target="right"><?= $this->translate->_('Senarai Pengkelasan') ?></a></li>
							
							<li><a href="<?= SYSTEM_URL ?>/ppp/new/applynew" target="right"><?= $this->translate->_('Permohonan Baru') ?></a></li>
							<li><a href="<?= SYSTEM_URL ?>/ppp/classification/applynew/id/1" target="right"><?= $this->translate->_('Permohonan Pengkelasan') ?></a></li>
						</ul>
					</div>
				</div>
				
			</div>
			<br>
			<div align="center" style="margin-left: 20px;">
				<table width="100%"  border="0" cellspacing="1" cellpadding="5">
					<tr>
						<td align="left">
							<!-- START: LEFT BLOCK -->
							<div id="leftblock">
							<div id="leftdiv">
							<div id="left">
								<div class="moduletable">			
									<form>
										<div class="search">
											<input name="searchword" id="mod_search_searchword" maxlength="20" alt="search" class="inputbox" type="text" size="20" value="carian..."  onblur="if(this.value=='') this.value='carian...';" onfocus="if(this.value=='carian...') this.value='';" /><input type="submit" value="Cari" class="button"/>	
										</div>
									</form>		
								</div>
							</div>
							</div>
							</div>
							<!-- END: LEFT BLOCK -->
						</td>
						<td width="2%">&nbsp;</td>
					</tr>
				</table>
			</div>
			<br>
			<div align="center" style="margin-left: 20px;"><span style="font-size:10px">
			Jika terdapat sebarang masalah mengenai 
			sistem atau data, sila hubungi:
			<br><br> 
			<strong>Bahagian Pengurusan Maklumat</strong><br> 
			Aras 35, Menara Dato' Onn<br> 
			Pusat Dagangan Dunia Putra<br> 
			45 jalan Tun Ismail<br> 
			50695 Kuala Lumpur<br> 
			Telefon : 03-8886 4000<br> 
			Email: eSPIP@motour.gov.my<br> </span>
			</div>
		</td>
		<td width="13px" height="100%" valign="top" align="right" style="background:url(<?= IMAGES_PATH.$this->css ?>/nav_on_bg.gif) 100% repeat-y"></td>
	</tr>
</table>